############### English navigation ################

# main menu
[[main]]
name = "HOME"
url = "/"
weight = 1

[[main]]
name = "ABOUT"
url = "/about/"
weight = 2

# Dropdown menu
# [[main]]
# weight = 3
# name = "PARTNERS"
# hasChildren = true

# [[main]]
# parent = "PARTNERS"
# name = "BDRSuite"
# url = "/bdrsuite/"
# weight = 1

[[main]]
name = "POWERCLI"
url = "/2019/07/16/powercli-installation-updating-and-troubleshooting-tips/"
weight = 4

[[main]]
name = "TOOLS"
url = "/tools/"
weight = 4

# [[main]]
# name = "CONTACT"
# url = "contact/"
# weight = 5

[[footer]]
name = "About"
url = "about/"
weight = 1

# [[footer]]
# name = "Contact"
# url = "contact/"
# weight = 2

# [[footer]]
# name = "Privacy Policy"
# url = "privacy-policy/"
# weight = 3

# [[footer]]
# name = "Terms Conditions"
# url = "terms-conditions/"
# weight = 4
